### ISSUE TITLE
get your personal link, ilk çalıştırdığım zaman undefined dönüyor 

### ISSUE THREAD

**Issue by sevkioruc** [okandavut/reposlib#10]
Adımlar
1. Kullanıcı adımı giriyorum
2. Enter' a tıklıyorum
3. Get your personal link' e tıklıyorum

![Screenshot 2020-12-02 220747](https://user-images.githubusercontent.com/33834689/100920396-e745a180-348f-11eb-984f-ab4f3da3cd04.png)

**Comment by okandavut** [comment]
Selamlar, öncelikle ilginize teşekkür ederim. Ben de kontrol ettim en kısa sürede düzelteceğim. Emeğinize sağlık.

**Comment by sevkioruc** [comment]
Selamlar, sizinde emeğinize sağlık. İyi çalışmalar.
